# Site Information
site_name: Training
site_url: https://gooseberry.github.io/training/
site_author: Eric Desgroseilliers

#  Repository
repo_name: gooseberry/training
repo_url: https://github.com/gooseberry/training

# Copyright
copyright: Copyright &copy; 2022 Eric Desgroseilliers

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Configuration
theme:
    name: material
    favicon: assets/images/favicon.png
    icon: 
        logo: material/dumbbell
        admonition:
            bug: material/heart-pulse
            warning: material/weight-lifter
            example: material/yoga
            success: material/timer-outline
            quote: material/sleep
            abstract: material/yin-yang
        tag:
            str: material/weight-lifter
            arm: material/arm-flex
            dbl: material/dumbbell
            int: material/timer-outline
            crd: material/heart-pulse
            yoga: material/yoga
            nogear: material/run
        
    palette:

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: amber
          accent: amber
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: amber
          accent: amber
          toggle:
            icon: material/brightness-3
            name: Switch to light mode


    # Features
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.expand
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.indexes
        - toc.follow

# Extras
extra:
    tags:
        strength: str
        bicep: arm
        tricep: arm
        legs: arm
        chest: arm
        back: arm
        shoulder: arm
        core: arm
        TRX: dbl
        interval: int
        cardio: crd
        full-body: str
        yoga: yoga
        no-gear: nogear

# Extensions
markdown_extensions:
    - admonition
    - def_list
    - wikilinks
    - attr_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.snippets:
        base_path: 
            - "docs/assets/snippets"

# Plugins
plugins:
    - tags:
        tags_file: about/tags.md
    - search

# Page tree
nav:
    - Home: "index.md"
    - Programs: 
        - programs/index.md
        - TRX 1 Week Program: "programs/trx-1-week-program.md"
    - Workouts: 
        - workouts/index.md
        - 30-20-10 Full Body Workout 1: workouts/30-20-10-full-body-1.md
        - 60 to 10 Full Body Workout 1: "workouts/60-10-full-body-1.md"
        - Tabata Workout 1: workouts/tabata-1.md
        - TRX Back & Biceps: "workouts/trx-back-bicep.md"
        - TRX Chest & Triceps: "workouts/trx-chest-tricep.md"
        - TRX Legs & Shoulders: "workouts/trx-leg-shoulder.md"
    - Exercises:
        - exercises/index.md
        - 1 Up 2 Down: "exercises/1-up-2-down.md"
        - Ankle Touch: "exercises/ankle-touch.md"
        - Bear Push Up: "exercises/bear-push-up.md"
        - Bear Should Tap: "exercises/bear-shoulder-tap.md"
        - Bicycle: "exercises/bicycle.md"
        - Butt Kick: "exercises/butt-kick.md"
        - Burpee: "exercises/burpee.md"
        - Figure 8: "exercises/figure-8.md"
        - Flutter Kick: "exercises/flutter-kick.md"
        - Frog Squat: "exercises/frog-squat.md"
        - Heals to the Heavens: "exercises/heals-heaven.md"
        - High Knees: "exercises/high-knees.md"
        - Hollow Body Hold: "exercises/hollow-body.md"
        - In & Out Plank: "exercises/in-out-plank.md"
        - In & Out V-Sit: "exercises/in-out-v-sit.md"
        - Jack Knife: "exercises/jack-knife.md"
        - Jump Lunge: "exercises/jump-lunge.md"
        - Jump Squat: "exercises/jump-squat.md"
        - Mason Twist: "exercises/mason-twist.md"
        - Mountain Climber: "exercises/mountain-climber.md"
        - Plank Hip Swing: "exercises/plank-swing.md"
        - Plank Jacks: "exercises/plank-jacks.md"
        - Plank Shoulder Tap: "exercises/plank-shoulder-tap.md"
        - Plank Up-Down: "exercises/plank-up-down.md"
        - Pulse Squat: "exercises/pulse-squat.md"
        - Push Up: "exercises/push-up.md"
        - Reverse Tabletop Toe Touch: "exercises/reverse-tabletop-toe-touch.md"
        - Rocket Push Up: "exercises/rocket-push-up.md"
        - Shuffle: "exercises/shuffle.md"
        - Skater: "exercises/skater.md"
        - Slow Bicycle: "exercises/slow-bicycle.md"
        - Sock Slide: "exercises/sock-slide.md"
        - Squat Hold: "exercises/squat-hold.md"
        - Star Jump: "exercises/star-jump.md"
        - T-Push Up: "exercises/t-push-up.md"
        - TRX Bicep Clutch: "exercise/trx-bicep-clutch.md"
        - TRX Bicep Curl: "exercises/trx-bicep-curl.md"
        - TRX Chest Fly: "exercises/trx-chest-fly.md"
        - TRX Clock Press: "exercises/trx-clock-press.md"
        - TRX Close-Grip Press: "exercises/trx-close-press.md"
        - TRX Dip: "exercises/trx-dip.md"
        - TRX Face Pull: "exercises/trx-face-pull.md"
        - TRX Front Shoulder Raise: "exercise/trx-front-raise.md"
        - TRX Hamstring Curl: "exercises/trx-hamstring-curl.md"
        - TRX Inverted Row: "exercises/trx-inverted-row.md"
        - TRX Pike: "exercises/trx-pike.md"
        - TRX Pistol Squat: "exercises/trx-pistol-squat.md"
        - TRX Side Plank: "exercises/trx-side-plank.md"
        - TRX Single Arm Bicep Curl: "exercises/trx-1-arm-bicep.md"
        - TRX Single Arm Row: "exercises/trx-1-arm-row.md"
        - TRX Split Squat: "exercises/trx-split-squat.md"
        - TRX T: "exercises:trx-t.md"
        - TRX Tricep Extension: "exercises/trx-tricep-extension.md"
        - TRX Wide-Grip Chest Press: "exercises/trx-wide-chest-press.md"
        - TRX Y: "exercises/trx-y.md"
        - V-Sit Hold: "exercises/v-sit-hold.md"
    - Tips & Tricks:
        - tips/index.md
        - Balance vs Stability: "tips/balance-stability.md"
    - About:
        - about/index.md
        - Tags: "about/tags.md"
